print("My name is diwash sharma acharya")
print ("I love to play cricket.")
print ("I hate reading.")
print ("I started running python.")
print ("I love dogs.")
print ("I live in chitwan.")
print ("I am single.")
print ("I love to travel and hike.")
print ("I often ride bike.")
print ("I am vegeterian.")